### ISSUE TITLE
Conditional operators only count one instance.

### ISSUE THREAD

**Issue by chadcwilliams** [AutoResearch/equation-tree#1]
The conditional operators seem to always give a frequency count of 1. 

For example x_1 * x_2 * x_3 * x_4 * x_5 gives the tree:

![Screenshot_2023-08-16 17_27_40](https://github.com/AutoResearch/equation-tree/assets/26373111/fb3819d0-f2d7-4e3c-8ea3-cd98e4bbb51c)

and gives conditional operators: 
![Screenshot_2023-08-16 17_28_56](https://github.com/AutoResearch/equation-tree/assets/26373111/8cecec5b-e63f-4176-b4f5-3dca5eaa943e)

So, it only tracks the first instance of the conditional.

**Comment by younesStrittmatter** [comment]
I look into that.
